apiVersion: v1
kind: Pod # type of controller
metadata: # meta of the controller
  name: demo-server-from-yml
  labels: 
    app: webserver
spec:
  containers:
  - name: pod-server-demo
    image: jacksontmm/demo-server:v1
    ports:
      - containerPort: 8080