apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: apiserver
      images: jacksontmm/demo-server:v7
      volumeMounts:
        - name: persistance-demo
          mountPath: /tmp

  volumes:
    - name: persistance-demo
      presistanceVolumeName:
        claimName: persistance-claim
