apiVersion: v1
kind: Pod
metadata:
  name: web-server-v2
  labels:
    app: webserver
    tier: backend
spec:
  containers:
    - name: web-server
      image: jacksontmm/demo-server:v5
      ports:
        - name: pod-port
          containerPort: 8080
