apiVersion: v1
kind: Pod
metadata:
  name: web-server-v1
  labels:
    app: webserver
    tier: backend
spec:
  containers:
    - name: web-pod-v1
      image: jacksontmm/demo-server:v4
      ports:
        - name: pod-port
          containerPort: 8080
