apiVersion: v1
kind: Pod
metadata:
  name: demo-secret
  labels:
    app: demo-server
spec:
  containers:
    - name: demo-pod
      image: jacksontmm/demo-server:v3
      ports:
        - containerPort: 8080
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-from-yml
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-from-yml
              key: password
        
