apiVersion: v1
kind: Pod
metadata:
  name: demo-server
  labels:
    app: demo-server
spec:
  containers:
    - name: demo-pod
      image: jacksontmm/demo-server:v3
      ports:
        - containerPort: 8080
      volumeMounts: # amount file to pod
        - name: secret-volume
          mountPath: /etc/creds # which path to amount
          readOnly: true # read only data
  volumes: # amount what data to container
  - name: secret-volume # same as volumeMounts
    secret:
      secretName: demo-secret-from-file


