apiVersion: v1
kind: Pod
metadata:
  name: demo-server-secret
  labels:
    app: demo-server
spec:
  containers:
    - name: demo-pod
      image: jacksontmm/demo-server:v3
      ports: 
        - containerPort: 8080
      env: 
      - name: SECRET_USER_NAME
        valueFrom:
          secretKeyRef:
            name: demo-secret-from-file
            key: user.txt
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: demo-secret-from-file
            key: pw.txt
